name = "oil-assist"
main = "src/index.ts"
compatibility_date = "2025-04-01"

[vars]

[[routes]]
pattern = "oil.0037.us/*"
zone_name = "0037.us"

[[d1_databases]]
binding = "DB"
database_name = "oil-assist"
database_id = "4fafbb7c-ad39-4c44-bffc-1d537d5bebca"

[assets]
directory = "../dist"
not_found_handling = "single-page-application"
