name = "oil-assist"
main = "src/index.ts"
compatibility_date = "2025-04-01"

[observability]
enabled = true
head_sampling_rate = 1

[vars]
JWT_SECRET = "fo7JrLBHTitAuDUlSyL8YtUvmdZXgVKWv0Mhi5mpYpc="

[[d1_databases]]
binding = "DB"
database_name = "oil-assist"
database_id = "98ca0130-e513-439d-ad8f-d146b179c6d7"

[assets]
directory = "../dist"
not_found_handling = "single-page-application"
